matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: '12'

    - os: linux
      dist: bionic
      sudo: true
      language: node_js
      node_js: '12'
      addons:
        apt:
          packages:
            - libx11-dev
            - zlib1g-dev
            - libpng-dev
            - libxtst-dev

script:
  - npm run dist
